<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>10</LangVersion>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>FsHcl</PackageId>
    <Version>0.1.0</Version>
    <Authors>ryushiaok</Authors>
    <Description>A small typed HCL generation DSL for F#.</Description>
    <PackageTags>fsharp;hcl;terraform;dsl</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/ryushiaok/FsHcl</RepositoryUrl>
    <PackageProjectUrl>https://ryushiaok.github.io/FsHcl</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src/HclAst.fs" />
    <Compile Include="src/HclValue.fs" />
    <Compile Include="src/HclSyntax.fs" />
    <Compile Include="src/HclRender.fs" />
    <Compile Include="src/TerraformHcl.fs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
